
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


const Analytics = lazy(() => import("./pages/Analytics.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const Chat = lazy(() => import("./pages/Chat.tsx"));
const ContentAnalysis = lazy(() => import("./pages/ContentAnalysis.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const Documents = lazy(() => import("./pages/Documents.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const Signup = lazy(() => import("./pages/Signup.tsx"));
const Urls = lazy(() => import("./pages/Urls.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/analytics", element: <UserGuard><Analytics /></UserGuard>},
	{ path: "/", element: <App />},
	{ path: "/chat", element: <UserGuard><Chat /></UserGuard>},
	{ path: "/content-analysis", element: <UserGuard><ContentAnalysis /></UserGuard>},
	{ path: "/contentanalysis", element: <UserGuard><ContentAnalysis /></UserGuard>},
	{ path: "/dashboard", element: <UserGuard><Dashboard /></UserGuard>},
	{ path: "/documents", element: <UserGuard><Documents /></UserGuard>},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},
	{ path: "/signup", element: <UserGuard><Signup /></UserGuard>},
	{ path: "/urls", element: <UserGuard><Urls /></UserGuard>},

];
